In [2]:
# Numerical Python
import numpy as np

In [14]:
arr1 = np.arange(15).reshape(3, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
arr1.shape

(3, 5)

In [16]:
arr1.dtype

dtype('int32')

In [17]:
arr3 = np.zeros((3, 4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
arr4 = np.array(np.arange(1, 7).reshape(2, 3), dtype=np.float64)
arr5 = np.array(np.arange(7, 13).reshape(2, 3), dtype=np.float64)

In [23]:
print(arr4+arr5)

[[ 8. 10. 12.]
 [14. 16. 18.]]


In [24]:
print(arr4/arr5)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
